### PR TITLE
Fix invalid feed error and update to 5.0 event api

### LINKED ISSUE #1: [Bug] Error if no feed item
If there is zero feed items the plugin will error out

### PR DESCRIPTION
**Pull request by purbon**
This PR:

 - Fixes the case when there is an invalid feed, exceptions are now catched and logged.
 - Also add test for normal, valid but empty and invalid feeds use cases.
- And updates to use the 5.0 event api.

include code to be using the new logstash-core api, backport will be necessary.

fixes #1

### CODE REVIEW

**Comment by purbon** [comment]
@guyboertje your thoughts here are welcome.

**Comment by guyboertje** [comment]
@purbon - looks good so far.  Please make one of the failure fixtures an atom feed.

**Comment by purbon** [comment]
@guyboertje can do that, will look for examples.

**Comment by purbon** [comment]
@guyboertje added atom test as requested, also helped fixing a few issues 👍 , let me know what do you think.

**Comment by guyboertje** [comment]
LGTM

**Pull request closed without merging**
